name: Build Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-22.04
            name: "Ubuntu GCC-11"
            artifact: "ubuntu_gcc.7z"
            build_type: "RelWithDebInfo"
            cc: "clang-14"
            cxx: "clang++-14"
            archiver: "7z a"
            generators: "Unix Makefiles"
            build_dir: 'build'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@main
          
      - name: Prereq
        shell: bash
        run: |
          sudo apt update
          sudo apt install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
          sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
          
      - name: Goit
        shell: bash
        run: |
          mkdir ~/blender-git
          cd ~/blender-git
          git clone https://git.blender.org/blender.git

      - name: Deps
        shell: bash
        run: |
          cd ~/blender-git
          echo "install_deps help:"
          # ./blender/build_files/build_environment/install_deps.sh --help
          
          # ./blender/build_files/build_environment/install_deps.sh --with-embree
          # The above should work but doesn't, so we force-replace it in the shell script
          ex -s -c '%s/WITH_EMBREE=false/WITH_EMBREE=true/g|x' ./blender/build_files/build_environment/install_deps.sh
          ./blender/build_files/build_environment/install_deps.sh --with-embree
          
      - name: Init Cmake
        shell: bash
        run: 
          cmake ../blender \
              -DWITH_PYTHON_INSTALL=OFF \
              -DWITH_AUDASPACE=OFF \
              -DWITH_PYTHON_MODULE=ON
              
      - name: Make
        shell: bash
        run: |
          cd ~/blender-git/blender
          make update
          make
          #./bin/bpy/
        
      - uses: mxschmitt/action-tmate@v3
        name: CI
